export const DEMO_CATEGORIES = [
  { id: "cat-1", name: "Abbigliamento", color: "#3b82f6", icon: "Shirt" },
  { id: "cat-2", name: "Accessori", color: "#8b5cf6", icon: "Watch" },
  { id: "cat-3", name: "Scarpe", color: "#f59e0b", icon: "Footprints" },
  { id: "cat-4", name: "Cosmetica & Cura", color: "#ec4899", icon: "Sparkles" },
  { id: "cat-5", name: "Hi-Tech", color: "#10b981", icon: "Smartphone" },
];

export const DEMO_PRODUCTS = [
  {
    id: "prod-1",
    name: "T-Shirt Cotone Bio",
    sku: "TSH-001",
    barcode: "8001234567890",
    description: "100% Cotone organico pettinato, vestibilità regular",
    price: 29.9,
    vatRate: 22.0,
    stockQuantity: 45,
    categoryId: "cat-1",
    category: DEMO_CATEGORIES[0],
  },
  {
    id: "prod-2",
    name: "Felpa Minimal Zip",
    sku: "FLP-002",
    barcode: "8001234567891",
    description: "Felpa garzata con zip intera e tasche a filo",
    price: 69.0,
    vatRate: 22.0,
    stockQuantity: 22,
    categoryId: "cat-1",
    category: DEMO_CATEGORIES[0],
  },
  {
    id: "prod-3",
    name: "Zaino Urbano Waterproof",
    sku: "ZAI-003",
    barcode: "8001234567892",
    description: "Scomparto per laptop 15'' e finitura impermeabile",
    price: 89.0,
    vatRate: 22.0,
    stockQuantity: 14,
    categoryId: "cat-2",
    category: DEMO_CATEGORIES[1],
  },
  {
    id: "prod-4",
    name: "Occhiali da Sole Polarizzati",
    sku: "OCCH-004",
    barcode: "8001234567893",
    description: "Montatura ultra-leggera in acetato, protezione UV400",
    price: 55.0,
    vatRate: 22.0,
    stockQuantity: 18,
    categoryId: "cat-2",
    category: DEMO_CATEGORIES[1],
  },
  {
    id: "prod-5",
    name: "Sneakers Classic White",
    sku: "SNK-005",
    barcode: "8001234567894",
    description: "Pelle naturale con soletta anatomica memory foam",
    price: 95.0,
    vatRate: 22.0,
    stockQuantity: 12,
    categoryId: "cat-3",
    category: DEMO_CATEGORIES[2],
  },
  {
    id: "prod-6",
    name: "Profumo Essenza Legnosa 50ml",
    sku: "PRF-006",
    barcode: "8001234567895",
    description: "Note di cedro, ambra grigia e bergamotto calabrese",
    price: 74.5,
    vatRate: 22.0,
    stockQuantity: 9,
    categoryId: "cat-4",
    category: DEMO_CATEGORIES[3],
  },
  {
    id: "prod-7",
    name: "Cuffie Wireless ANC",
    sku: "CUF-007",
    barcode: "8001234567896",
    description: "Cancellazione attiva del rumore e 35h di autonomia",
    price: 129.0,
    vatRate: 22.0,
    stockQuantity: 8,
    categoryId: "cat-5",
    category: DEMO_CATEGORIES[4],
  },
  {
    id: "prod-8",
    name: "Powerbank MagSafe 10.000mAh",
    sku: "POW-008",
    barcode: "8001234567897",
    description: "Ricarica wireless rapida 15W con aggancio magnetico",
    price: 39.9,
    vatRate: 22.0,
    stockQuantity: 25,
    categoryId: "cat-5",
    category: DEMO_CATEGORIES[4],
  },
];

export const DEMO_CUSTOMERS = [
  {
    id: "cust-1",
    firstName: "Marco",
    lastName: "Rossi",
    phone: "+39 333 1234567",
    email: "marco.rossi@email.it",
    fidelityCardNumber: "FID-88219",
    fidelityPoints: 240,
    tier: "GOLD",
  },
  {
    id: "cust-2",
    firstName: "Laura",
    lastName: "Bianchi",
    phone: "+39 340 9876543",
    email: "laura.bianchi@email.it",
    fidelityCardNumber: "FID-44120",
    fidelityPoints: 115,
    tier: "SILVER",
  },
  {
    id: "cust-3",
    firstName: "Alessandro",
    lastName: "Moretti",
    phone: "+39 349 1122334",
    email: "a.moretti@email.it",
    fidelityCardNumber: "FID-10992",
    fidelityPoints: 650,
    tier: "VIP",
  },
];

export const DEMO_SALES = [
  {
    id: "sale-1",
    saleNumber: "SCT-2026-0001",
    subtotal: 98.9,
    taxAmount: 17.83,
    discountAmount: 0.0,
    totalAmount: 98.9,
    paymentMethod: "POS_CARTA",
    status: "COMPLETED",
    cashierName: "Cassa 1 - Operatore Demo",
    customerId: "cust-1",
    customer: DEMO_CUSTOMERS[0],
    pointsEarned: 10,
    createdAt: new Date().toISOString(),
    items: [
      {
        id: "item-1",
        saleId: "sale-1",
        productId: "prod-1",
        productName: "T-Shirt Cotone Bio",
        unitPrice: 29.9,
        quantity: 1,
        vatRate: 22.0,
        subtotal: 29.9,
      },
      {
        id: "item-2",
        saleId: "sale-1",
        productId: "prod-2",
        productName: "Felpa Minimal Zip",
        unitPrice: 69.0,
        quantity: 1,
        vatRate: 22.0,
        subtotal: 69.0,
      },
    ],
  },
  {
    id: "sale-2",
    saleNumber: "SCT-2026-0002",
    subtotal: 129.0,
    taxAmount: 23.26,
    discountAmount: 0.0,
    totalAmount: 129.0,
    paymentMethod: "CONTANTI",
    status: "COMPLETED",
    cashierName: "Cassa 1 - Operatore Demo",
    customerId: "cust-2",
    customer: DEMO_CUSTOMERS[1],
    pointsEarned: 15,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    items: [
      {
        id: "item-3",
        saleId: "sale-2",
        productId: "prod-7",
        productName: "Cuffie Wireless ANC",
        unitPrice: 129.0,
        quantity: 1,
        vatRate: 22.0,
        subtotal: 129.0,
      },
    ],
  },
];
